### ISSUE TITLE
background image not displaying on Chrome/Edge/Firefox

### ISSUE THREAD

**Issue by Pranta-Palit** [bradtraversy/btre_project#33]
Even after fixing the codes [here](https://github.com/bradtraversy/btre_project/pull/19/commits/a3bdfedb274ea0e679fb114648bc2e0f0d30f488), the issue is not fixed yet. The background image is not visible in any browser. Please help.

**Comment by anurag-dub3y** [comment]
It's been more that two years but do you remember how you were able to fix it?
