### ISSUE TITLE
Invalid Property Value on background

### ISSUE THREAD

**Issue by bpncodes** [bradtraversy/btre_project#9]
I can't see the background image on the webpage for any of the pages but the style.ss is working fine. This code is giving me an 'invalid property value' in Chrome. 
![Screenshot (77)](https://user-images.githubusercontent.com/37392883/71411702-776c4b80-2670-11ea-958a-6ce17200e67b.png)
![Screenshot (78)](https://user-images.githubusercontent.com/37392883/71411703-7804e200-2670-11ea-903c-7c05721c4363.png)
![Screenshot (81)](https://user-images.githubusercontent.com/37392883/71411704-7804e200-2670-11ea-8d09-b38b04fa5b5c.png)

**Comment by NeerajSajwan096** [comment]
in style.css background url(fixed/center) change it to only fixed

**Comment by bpncodes** [comment]
Now I've switched my system to ubuntu and I cant collect static files.

STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATIC_URL = '/static/'
STATICFILE_DIRS = [ 
    os.path.join(BASE_DIR, 'btre/static/' )
][
![Screenshot from 2020-01-30 19-29-29](https://user-images.githubusercontent.com/37392883/73455885-e38c4e80-4396-11ea-9e14-3dac6b8c9182.png)
](url)

**Comment by bpncodes** [comment]
Yup that did the trick. Although I don't understand why cover/fixed was not working anywho thanks !!

**Comment by AntMam** [comment]
This didn't work for me. It seems to be something with Google Chrome as it works fine in Safari.  Any thoughts to get it to work in both?
